title: Talapas Workshop Archive
description: Talapas Resources and Lesson Materials
theme: just-the-docs

url: https://wintere.github.io/introhpc-archive/
color_scheme: uo

aux_links:
  Talapas Support: https://hpcrcf.atlassian.net/servicedesk/customer/portal/1
  Talapas Documentation: https://uoracs.github.io/talapas2-knowledge-base/
  Data Services Consults: https://uoregon.libcal.com/appointments/data_services

ga_tracking: G-5SQ751NSV8
ga_tracking_anonymize_ip: true