title: Talapas Workshop Archive
description: Talapas Resources and Lesson Materials
theme: just-the-docs

url: https://wintere.github.io/introhpc-archive/
color_scheme: light

aux_links:
  Talapas Documentation: https://hpcrcf.atlassian.net/wiki/spaces/TW/pages/2755757568/Quick+Start+Guide
